name: moviestar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/moviestar-logo.png"

flutter:
  uses-material-design: true
  assets: 
    - assets/images/moviestar-logo.png
    - assets/images/moviestar.png
    - assets/images/unknown-person.jpg
    - assets/images/movies.png
